data_path: C:\Users\navee\Documents\My Stuff\Georgia Tech\Classes\CS7643-Deep_Learning\FastMRI\fastMRI\fastmri_data
mask_type: random
center_fractions: [0.08]
accelerations: [4]
challenge: singlecoil

# only for pace cluster!
use_gpu: True 

# FastMriDataModule args
batch_size: 1
num_workers: 0 
test_split: val            # can be 'val' or 'test'
test_path: C:\Users\navee\Documents\My Stuff\Georgia Tech\Classes\CS7643-Deep_Learning\FastMRI\fastMRI\fastmri_data\singlecoil_test
sample_rate: 0.1          # optional: subsample % for training (e.g. 0.05)

# make it reproducable 
seed: 42 # default is 42

in_chans: 1
out_chans: 1
chans: 128 #32
num_pool_layers: 4 #5 # default 4
drop_prob: 0.0
lr: 0.001
lr_step_size: 40
lr_gamma: 0.1
weight_decay: 0.0
gpus: 1
distributed_backend: ddp
max_epochs: 30
default_root_dir: C:\Users\navee\Documents\My Stuff\Georgia Tech\Classes\CS7643-Deep_Learning\FastMRI\fastMRI\sobel_roi_unet_checkpoints

# roi loss 
alpha: 1 # 1 means no mask
# roi_size: 128


# checkpoint
resume: False # false for tuning

# sobel stuff
# sobel_threshold: 0.4
# dilation_size: 9
sobel_threshold: 0.3
dilation_size: 9
